---
- name: obsidian - setup vault
  tags: always
  block:
    - name: obsidian - create vault
      file:
        path: '{{ vault_dir }}/.obsidian'
        state: directory
        mode: '0755'

    - name: obsidian - own-packages
      include_tasks: build-obsidian-package.yml
      loop:
        - obsidian-latex
        - obsidian-text-expander

    - name: obsidian - plugins, themes, snippets, scripts
      file:
        src: '{{ ansible_env.PWD }}/obsidian/{{ item }}'
        path: '{{ vault_dir }}/.obsidian/{{ item }}'
        state: link
      loop:
        - plugins
        - themes
        - snippets
        - scripts

    - name: obsidian - settings
      file:
        src: '{{ ansible_env.PWD }}/obsidian/settings/{{ item }}'
        path: '{{ vault_dir }}/.obsidian/{{ item }}'
        state: link
      loop:
        - config
        - daily-notes.json
        - global-search.json
