#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  connection: local
  tasks:
  - debug:
      msg: Check we are running in the directory of the script
    failed_when: not ansible_env.PWD.endswith('/config')
  - include_tasks: tasks/dotfiles.yml
