---
- name: dotfiles dirs
  file:
    path: '~/{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - .ipython/profile_default/startup
    - .oh-my-zsh/custom/plugins

- name: dotfiles links
  file:
    src: '{{ ansible_env.PWD }}/dotfiles/{{ item }}'
    path: '~/{{ item }}'
    state: link
  loop:
    - .zshrc
    - .ipython/profile_default/ipython_config.py
    - .ipython/profile_default/startup/00-autoreload.ipy
    - .ipython/profile_default/startup/01-pylab.ipy
    - .ipython/profile_default/startup/02-imports.py
    - .oh-my-zsh/custom/plugins/zsh-autosuggestions
