---
- name: dotfiles dirs
  file:
    path: '~/.{{ item }}'
    state: directory
    mode: '0755'
  loop: []

- name: dotfiles links
  file:
    src: '{{ ansible_env.PWD }}/dotfiles/{{ item }}'
    path: '~/.{{ item }}'
    state: link
  loop:
    - zshrc
