---
- name: inkscape - get user data directory
  tags: inkscape
  command: inkscape --user-data-directory
  register: inkscape_user_data_directory_command
  changed_when: false

- name: inkscape - set fact for user data directory
  tags: inkscape
  set_fact:
    inkscape_user_data_directory: '{{ inkscape_user_data_directory_command.stdout }}'

- name: inkscape - get system data directory
  tags: inkscape
  command: inkscape --system-data-directory
  register: inkscape_system_data_directory_command
  changed_when: false

- name: inkscape - set fact for system data directory
  tags: inkscape
  set_fact:
    inkscape_system_data_directory: '{{ inkscape_system_data_directory_command.stdout }}'

- name: inkscape - ui
  tags: inkscape
  file:
    src: '{{ ansible_env.PWD }}/inkscape/ui/{{ item }}'
    path: '{{ inkscape_system_data_directory }}/ui/{{ item }}'
    state: link
  loop:
    - toolbar-commands.ui
    - toolbar-tool.ui
    - toolbox.xml
