---
- name: obsidian - create vault
  tags: obsidian
  file:
    path: '~/Documents/vault/.obsidian'
    state: directory
    mode: '0755'

- name: obsidian - own-packages
  tags: obsidian
  include_tasks: obsidian-build-package.yml
  loop:
    - obsidian-latex
    - obsidian-text-expander

- name: obsidian - plugins, themes, snippets
  tags: obsidian
  file:
    src: '{{ ansible_env.PWD }}/obsidian/{{ item }}'
    path: '~/Documents/vault/.obsidian/{{ item }}'
    state: link
  loop:
    - plugins
    - themes
    - snippets

- name: obsidian - settings
  tags: obsidian
  file:
    src: '{{ ansible_env.PWD }}/obsidian/settings/{{ item }}'
    path: '~/Documents/vault/.obsidian/{{ item }}'
    state: link
  loop:
    - config
    - daily-notes.json
    - global-search.json
