- name: obsidian - setup vaults
  tags: obsidian
  block:
    - name: obsidian - setup main vaults
      tags: obsidian, obsidian_main_vaults
      include_tasks: utils/setup-obsidian-vault.yml
      loop: '{{ vaults.main }}'
      loop_control:
        loop_var: vault_dir

    - name: obsidian - setup main vaults
      tags: obsidian, obsidian_additional_vaults
      include_tasks: utils/setup-obsidian-vault.yml
      loop: '{{ vaults.additional }}'
      loop_control:
        loop_var: vault_dir
