---
name: CI

on: [push]

env:
  ANSIBLE_VERSION: 3.0.0
  ANSIBLE_LINT_VERSION: 5.0.2
  YAMLLINT_VERSION: 1.25.0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install ansible
        run: sudo apt-get install -y ansible=={{ ANSIBLE_VERSION }}

      - name: Install linters
        run: sudo apt-get install -y ansible-lint=={{ ANSIBLE_LINT_VERSION }} yamllint=={{ YAMLLINT_VERSION }}

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint

  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install ansible.
        run: brew install ansible=={{ ANSIBLE_VERSION }}

      - name: Test the playbook's syntax.
        run: ansible-playbook playbook.yml --syntax-check

      - name: Test the playbook.
        run: ansible-playbook playbook.yml
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Idempotence check.
        run: |
          idempotence=$(mktemp)
          ansible-playbook playbook.yml | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: '1'
